/**
 * Prebuild Script — Fetch Categories from Crawler API
 *
 * Runs before `next build` to pull the latest site data from the
 * jtokki-crawler Worker API and write it to src/data/categories.ts.
 *
 * If the API is unavailable, the existing static data is preserved
 * as a safe fallback.
 *
 * Usage: tsx scripts/fetch-categories.ts
 * Env:   CRAWLER_API_URL, CRAWLER_API_KEY (optional)
 */

import { writeFileSync, readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Load .env.local (tsx doesn't auto-load like Next.js)
const envPath = resolve(__dirname, '../.env.local');
if (existsSync(envPath)) {
  const envContent = readFileSync(envPath, 'utf-8');
  for (const line of envContent.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx > 0) {
      const key = trimmed.slice(0, eqIdx);
      const val = trimmed.slice(eqIdx + 1);
      if (!process.env[key]) process.env[key] = val;
    }
  }
}

// ── Config ─────────────────────────────────────────
const API_URL = process.env.CRAWLER_API_URL || process.env.NEXT_PUBLIC_CRAWLER_API_URL || '';
const API_KEY = process.env.CRAWLER_API_KEY || process.env.NEXT_PUBLIC_CRAWLER_API_KEY || '';
const OUTPUT_PATH = resolve(__dirname, '../src/data/categories.ts');

// ── Types ──────────────────────────────────────────
interface CrawlerSite {
  name: string;
  currentUrl: string;
  status: string;
  latency: number | null;
  lastChecked: string | null;
}

interface CrawlerCategory {
  category: string;
  categoryTitle: string;
  icon: string;
  sites: CrawlerSite[];
  uptime: number;
}

interface CrawlerResponse {
  ok: boolean;
  timestamp: string;
  data: CrawlerCategory[];
}

// ── Fetch ──────────────────────────────────────────
async function fetchFromApi(): Promise<CrawlerResponse | null> {
  if (!API_URL) {
    console.log('⚠️  No CRAWLER_API_URL set — skipping API fetch');
    return null;
  }

  console.log(`🔄 Fetching site data from ${API_URL}/api/sites...`);

  const headers: Record<string, string> = {};
  if (API_KEY) {
    headers['X-API-Key'] = API_KEY;
  }

  try {
    const res = await fetch(`${API_URL}/api/sites`, {
      headers,
      signal: AbortSignal.timeout(15000),
    });

    if (!res.ok) {
      console.error(`❌ API returned HTTP ${res.status}`);
      return null;
    }

    const data = (await res.json()) as CrawlerResponse;

    if (!data.ok || !data.data?.length) {
      console.error('❌ API response invalid or empty');
      return null;
    }

    console.log(`✅ Received ${data.data.length} categories, ${data.data.reduce((n, c) => n + c.sites.length, 0)} sites`);
    return data;
  } catch (err) {
    console.error('❌ API fetch failed:', err instanceof Error ? err.message : err);
    return null;
  }
}

// ── Generate TypeScript ────────────────────────────
function generateCategoriesTs(apiData: CrawlerResponse): string {
  const lines: string[] = [
    "// Auto-generated by scripts/fetch-categories.ts",
    `// Last updated: ${apiData.timestamp}`,
    "// DO NOT EDIT MANUALLY — this file is overwritten on each build.",
    "",
    "export type SiteStatus = 'live' | 'changed' | 'dead';",
    "",
    "export interface Site {",
    "  name: string;",
    "  url: string;",
    "  status: SiteStatus;",
    "  latency: number | null;",
    "  /** ISO date — when the URL was last changed */",
    "  changedAt?: string;",
    "  /** Previous URL before the change */",
    "  previousUrl?: string;",
    "}",
    "",
    "export interface Category {",
    "  id: string;",
    "  icon: string;",
    "  title: string;",
    "  sites: Site[];",
    "  uptime: number;",
    "  lastCheck: string;",
    "}",
    "",
    "export const CATEGORIES: Category[] = ",
  ];

  const categories = apiData.data.map((cat) => ({
    id: cat.category,
    icon: cat.icon,
    title: cat.categoryTitle,
    sites: cat.sites.map((s) => ({
      name: s.name,
      url: s.currentUrl,
      status: (s.status === 'unknown' ? 'live' : s.status) as 'live' | 'changed' | 'dead',
      latency: s.latency,
    })),
    uptime: cat.uptime,
    lastCheck: getRelativeTime(cat.sites[0]?.lastChecked),
  }));

  lines.push(JSON.stringify(categories, null, 2) + ';');
  lines.push('');

  return lines.join('\n');
}

function getRelativeTime(isoDate: string | null | undefined): string {
  if (!isoDate) return '방금 전';
  const now = Date.now();
  const then = new Date(isoDate).getTime();
  const diffMin = Math.floor((now - then) / 60000);

  if (diffMin < 1) return '방금 전';
  if (diffMin < 60) return `${diffMin}분 전`;
  const diffHr = Math.floor(diffMin / 60);
  if (diffHr < 24) return `${diffHr}시간 전`;
  const diffDay = Math.floor(diffHr / 24);
  return `${diffDay}일 전`;
}

// ── Main ───────────────────────────────────────────
async function main() {
  console.log('\n🐰 jtokki prebuild — fetching latest site data\n');

  const apiData = await fetchFromApi();

  if (!apiData) {
    console.log('📋 Keeping existing categories.ts as fallback');
    // Verify the file exists
    try {
      readFileSync(OUTPUT_PATH, 'utf-8');
      console.log('✅ Existing categories.ts found — build will proceed with static data');
    } catch {
      console.error('❌ No existing categories.ts found! Build may fail.');
      process.exit(1);
    }
    return;
  }

  const content = generateCategoriesTs(apiData);
  writeFileSync(OUTPUT_PATH, content, 'utf-8');
  console.log(`✅ categories.ts updated with ${apiData.data.length} categories`);
  console.log(`📁 Written to: ${OUTPUT_PATH}\n`);
}

main().catch((err) => {
  console.error('❌ Prebuild script failed:', err);
  // Don't exit with error — let the build continue with existing data
  console.log('📋 Build will proceed with existing categories.ts');
});
