// Auto-generated by scripts/fetch-categories.ts
// Last updated: 2026-06-23T10:25:07.884Z
// DO NOT EDIT MANUALLY — this file is overwritten on each build.

export type SiteStatus = 'live' | 'changed' | 'dead';

export interface Site {
  name: string;
  url: string;
  status: SiteStatus;
  latency: number | null;
  /** ISO date — when the URL was last changed */
  changedAt?: string;
  /** Previous URL before the change */
  previousUrl?: string;
}

export interface Category {
  id: string;
  icon: string;
  title: string;
  sites: Site[];
  uptime: number;
  lastCheck: string;
}

export const CATEGORIES: Category[] = 
[
  {
    "id": "webtoon",
    "icon": "📖",
    "title": "웹툰",
    "sites": [
      {
        "name": "뉴토끼",
        "url": "https://toki25.com",
        "status": "live",
        "latency": 97
      },
      {
        "name": "늑대닷컴",
        "url": "https://wfwf473.com",
        "status": "live",
        "latency": 119
      },
      {
        "name": "툰코",
        "url": "https://tkor128.com",
        "status": "live",
        "latency": 14
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "drama",
    "icon": "📺",
    "title": "영화/드라마/애니",
    "sites": [
      {
        "name": "티비위키",
        "url": "https://tvwiki300.com",
        "status": "live",
        "latency": 89
      },
      {
        "name": "애니라이프",
        "url": "https://anilife.app",
        "status": "live",
        "latency": 72
      },
      {
        "name": "후후티비",
        "url": "https://cw.hoohootv418.xyz",
        "status": "live",
        "latency": 285
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "sports",
    "icon": "🏀",
    "title": "스포츠 중계",
    "sites": [
      {
        "name": "헐크티비",
        "url": "https://www.hulk24.com",
        "status": "live",
        "latency": 29
      },
      {
        "name": "킹콩티비",
        "url": "https://kktv247.com",
        "status": "live",
        "latency": 610
      },
      {
        "name": "챔스티비",
        "url": "https://sportsentrysolutions.com",
        "status": "live",
        "latency": 567
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "BJ",
    "icon": "🔞",
    "title": "BJ라이브",
    "sites": [
      {
        "name": "팬더티비",
        "url": "https://www.pandalive.co.kr",
        "status": "live",
        "latency": 1492
      },
      {
        "name": "스트립챗",
        "url": "https://stripchat.com",
        "status": "live",
        "latency": 162
      },
      {
        "name": "팝콘티비",
        "url": "https://www.popkontv.com",
        "status": "live",
        "latency": 1480
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "adult-ko",
    "icon": "🔞",
    "title": "성인-국내",
    "sites": [
      {
        "name": "야스닷컴",
        "url": "https://yasyadong01.tv/",
        "status": "live",
        "latency": 645
      },
      {
        "name": "밤포탈",
        "url": "https://bampt4.com",
        "status": "live",
        "latency": 189
      }
    ],
    "uptime": 66.7,
    "lastCheck": "9시간 전"
  },
  {
    "id": "adult-int",
    "icon": "🔞",
    "title": "성인-해외",
    "sites": [
      {
        "name": "SpankBang",
        "url": "https://spankbang.com",
        "status": "live",
        "latency": 48
      },
      {
        "name": "XVideos",
        "url": "https://xvideos.com",
        "status": "live",
        "latency": 182
      },
      {
        "name": "XHamster",
        "url": "https://xhamster.com",
        "status": "live",
        "latency": 445
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "toto-int",
    "icon": "🎰",
    "title": "토토-코인",
    "sites": [
      {
        "name": "FOMO",
        "url": "https://fomolinks.com/dxdc7oqlu",
        "status": "live",
        "latency": 94
      },
      {
        "name": "Stake",
        "url": "https://stake.com/?c=NzowA8oB",
        "status": "live",
        "latency": 90
      },
      {
        "name": "BC.game",
        "url": "https://bc.game/i-4c05n8n5x-n/",
        "status": "live",
        "latency": 315
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "op",
    "icon": "💕",
    "title": "유흥",
    "sites": [
      {
        "name": "건마에반하다",
        "url": "https://www.gunmalove.com",
        "status": "live",
        "latency": 28
      },
      {
        "name": "오피가이드",
        "url": "https://opga039.com",
        "status": "live",
        "latency": 26
      },
      {
        "name": "마사지맵",
        "url": "https://mamap.co.kr",
        "status": "live",
        "latency": 1219
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  }
];

export interface HistoryEntry {
  date: string;
  from: string;
  to: string;
}

export const NEWTOKI_HISTORY: HistoryEntry[] = 
[
  {
    "date": "2026-06-22",
    "from": "sbxh9.com",
    "to": "toki25.com"
  },
  {
    "date": "2026-06-20",
    "from": "getunicorn.app",
    "to": "sbxh9.com"
  },
  {
    "date": "2026-06-19",
    "from": "sbxh8.com",
    "to": "getunicorn.app"
  },
  {
    "date": "2026-06-17",
    "from": "sbxh7.com",
    "to": "sbxh8.com"
  },
  {
    "date": "2026-06-15",
    "from": "newtoki1.org",
    "to": "sbxh7.com"
  }
];
