// Auto-generated by scripts/fetch-categories.ts
// Last updated: 2026-05-16T22:45:20.495Z
// DO NOT EDIT MANUALLY — this file is overwritten on each build.

export type SiteStatus = 'live' | 'changed' | 'dead';

export interface Site {
  name: string;
  url: string;
  status: SiteStatus;
  latency: number | null;
  /** ISO date — when the URL was last changed */
  changedAt?: string;
  /** Previous URL before the change */
  previousUrl?: string;
}

export interface Category {
  id: string;
  icon: string;
  title: string;
  sites: Site[];
  uptime: number;
  lastCheck: string;
}

export const CATEGORIES: Category[] = 
[
  {
    "id": "webtoon",
    "icon": "📖",
    "title": "웹툰",
    "sites": [
      {
        "name": "뉴토끼",
        "url": "https://sbxh1.com",
        "status": "live",
        "latency": 8
      },
      {
        "name": "늑대닷컴",
        "url": "https://wfwf452.com",
        "status": "live",
        "latency": 745
      },
      {
        "name": "툰코",
        "url": "https://tkor117.com",
        "status": "live",
        "latency": 208
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "drama",
    "icon": "📺",
    "title": "영화/드라마/애니",
    "sites": [
      {
        "name": "티비위키",
        "url": "https://tvwiki.app",
        "status": "live",
        "latency": 11
      },
      {
        "name": "애니라이프",
        "url": "https://anilife.app",
        "status": "live",
        "latency": 9
      },
      {
        "name": "후후티비",
        "url": "https://gc.hoohootv399.xyz",
        "status": "live",
        "latency": 340
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "sports",
    "icon": "🏀",
    "title": "스포츠 중계",
    "sites": [
      {
        "name": "헐크티비",
        "url": "https://www.hulk24.com",
        "status": "live",
        "latency": 8
      },
      {
        "name": "킹콩티비",
        "url": "https://kktv247.com",
        "status": "live",
        "latency": 200
      },
      {
        "name": "챔스티비",
        "url": "https://sportsentrysolutions.com",
        "status": "live",
        "latency": 655
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "BJ",
    "icon": "🔞",
    "title": "BJ라이브",
    "sites": [
      {
        "name": "팬더티비",
        "url": "https://www.pandalive.co.kr",
        "status": "live",
        "latency": 641
      },
      {
        "name": "스트립챗",
        "url": "https://stripchat.com",
        "status": "live",
        "latency": 183
      },
      {
        "name": "팝콘티비",
        "url": "https://www.popkontv.com",
        "status": "live",
        "latency": 1123
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "adult-ko",
    "icon": "🔞",
    "title": "성인-국내",
    "sites": [
      {
        "name": "야스닷컴",
        "url": "https://yasyadong01.tv/",
        "status": "live",
        "latency": 10
      },
      {
        "name": "오늘보지 (AI 영상)",
        "url": "https://cu2day.com",
        "status": "live",
        "latency": 364
      },
      {
        "name": "밤포탈",
        "url": "https://bampt3.com",
        "status": "live",
        "latency": 232
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "adult-int",
    "icon": "🔞",
    "title": "성인-해외",
    "sites": [
      {
        "name": "SpankBang",
        "url": "https://spankbang.com",
        "status": "live",
        "latency": 32
      },
      {
        "name": "XVideos",
        "url": "https://xvideos.com",
        "status": "live",
        "latency": 1018
      },
      {
        "name": "XHamster",
        "url": "https://xhamster.com",
        "status": "live",
        "latency": 528
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "toto-int",
    "icon": "🎰",
    "title": "토토-코인",
    "sites": [
      {
        "name": "FOMO",
        "url": "https://fomolinks.com/dxdc7oqlu",
        "status": "live",
        "latency": 25
      },
      {
        "name": "Stake",
        "url": "https://stake.com/?c=NzowA8oB",
        "status": "live",
        "latency": 25
      },
      {
        "name": "BC.game",
        "url": "https://bc.game/i-4c05n8n5x-n/",
        "status": "live",
        "latency": 109
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  },
  {
    "id": "op",
    "icon": "💕",
    "title": "유흥",
    "sites": [
      {
        "name": "건마에반하다",
        "url": "https://www.gunmalove.com",
        "status": "live",
        "latency": 8
      },
      {
        "name": "오피가이드",
        "url": "https://opga038.com",
        "status": "live",
        "latency": 8
      },
      {
        "name": "마사지맵",
        "url": "https://mamap.co.kr",
        "status": "live",
        "latency": 493
      }
    ],
    "uptime": 100,
    "lastCheck": "9시간 전"
  }
];
